(define (problem depotprob103) (:domain Depot)
(:objects
	depot0 depot1 depot2 depot3 - depot
	distributor0 distributor1 distributor2 distributor3 - distributor
	truck0 truck1 truck2 truck3 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 - pallet
	crate0 crate1 crate2 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate1)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 depot3)
	(clear pallet3)
	(at pallet4 distributor0)
	(clear pallet4)
	(at pallet5 distributor1)
	(clear crate2)
	(at pallet6 distributor2)
	(clear pallet6)
	(at pallet7 distributor3)
	(clear pallet7)
	(at truck0 depot3)
	(= (current_load truck0) 0)
	(= (load_limit truck0) 439.0)
	(at truck1 depot3)
	(= (current_load truck1) 0)
	(= (load_limit truck1) 209.0)
	(at truck2 distributor2)
	(= (current_load truck2) 0)
	(= (load_limit truck2) 309.0)
	(at truck3 distributor0)
	(= (current_load truck3) 0)
	(= (load_limit truck3) 246.0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 depot3)
	(available hoist3)
	(at hoist4 distributor0)
	(available hoist4)
	(at hoist5 distributor1)
	(available hoist5)
	(at hoist6 distributor2)
	(available hoist6)
	(at hoist7 distributor3)
	(available hoist7)
	(at crate0 distributor1)
	(on crate0 pallet5)
	(= (weight crate0) 7)
	(at crate1 depot0)
	(on crate1 pallet0)
	(= (weight crate1) 89)
	(at crate2 distributor1)
	(on crate2 crate0)
	(= (weight crate2) 17)
	(= (fuel-cost) 0)
)

(:goal (and
		(>= (current_load truck0) (+ (weight crate1) (weight crate2)))
        (>= (current_load truck1) (weight crate0))
	)
)

(:metric minimize (total-time)))
