(define (domain rover)
(:requirements :typing :negative-preconditions :equality)
(:types 	rover waypoint store camera mode lander objective - object
)

(:predicates (at ?x - rover ?y - waypoint)
	(at_lander ?x - lander ?y - waypoint)
	(can_traverse ?r - rover ?x - waypoint ?y - waypoint)
	(equipped_for_soil_analysis ?r - rover)
	(equipped_for_rock_analysis ?r - rover)
	(equipped_for_imaging ?r - rover)
	(empty ?s - store)
	(have_rock_analysis ?r - rover ?w - waypoint)
	(have_soil_analysis ?r - rover ?w - waypoint)
	(full ?s - store)
	(calibrated ?c - camera ?r - rover)
	(supports ?c - camera ?m - mode)
	(available ?r - rover)
	(visible ?w - waypoint ?p - waypoint)
	(have_image ?r - rover ?o - objective ?m - mode)
	(communicated_soil_data ?w - waypoint)
	(communicated_rock_data ?w - waypoint)
	(communicated_image_data ?o - objective ?m - mode)
	(at_soil_sample ?w - waypoint)
	(at_rock_sample ?w - waypoint)
	(visible_from ?o - objective ?w - waypoint)
	(store_of ?s - store ?r - rover)
	(calibration_target ?i - camera ?o - objective)
	(on_board ?i - camera ?r - rover)
	(channel_free ?l - lander)
)

(:action communicate_rock_data-navigate
	:parameters (?x_1 - rover ?py - waypoint ?z_1 - waypoint ?r_0 - rover ?l_0 - lander ?x_0 - waypoint ?y_0 - waypoint)
	:precondition (and (at ?r_0 ?x_0)
	(at ?x_1 ?py)
	(at_lander ?l_0 ?y_0)
	(at_rock_sample ?x_0)
	(at_soil_sample ?y_0)
	(at_soil_sample ?z_1)
	(available ?r_0)
	(available ?x_1)
	(can_traverse ?x_1 ?py ?z_1)
	(can_traverse ?x_1 ?z_1 ?py)
	(channel_free ?l_0)
	(communicated_rock_data ?y_0)
	(equipped_for_imaging ?r_0)
	(equipped_for_imaging ?x_1)
	(equipped_for_rock_analysis ?r_0)
	(equipped_for_soil_analysis ?x_1)
	(have_rock_analysis ?r_0 ?py)
	(have_soil_analysis ?x_1 ?py)
	(not (at ?r_0 ?py))
	(not (at ?r_0 ?y_0))
	(not (at ?x_1 ?z_1))
	(not (at_lander ?l_0 ?py))
	(not (at_lander ?l_0 ?x_0))
	(not (at_rock_sample ?py))
	(not (at_rock_sample ?y_0))
	(not (at_rock_sample ?z_1))
	(not (at_soil_sample ?py))
	(not (at_soil_sample ?x_0))
	(not (can_traverse ?r_0 ?py ?x_0))
	(not (can_traverse ?r_0 ?py ?y_0))
	(not (can_traverse ?r_0 ?x_0 ?py))
	(not (can_traverse ?r_0 ?x_0 ?y_0))
	(not (can_traverse ?r_0 ?y_0 ?py))
	(not (can_traverse ?r_0 ?y_0 ?x_0))
	(not (communicated_rock_data ?py))
	(not (communicated_rock_data ?x_0))
	(not (communicated_rock_data ?z_1))
	(not (communicated_soil_data ?py))
	(not (communicated_soil_data ?x_0))
	(not (communicated_soil_data ?y_0))
	(not (communicated_soil_data ?z_1))
	(not (equipped_for_rock_analysis ?x_1))
	(not (equipped_for_soil_analysis ?r_0))
	(not (have_rock_analysis ?r_0 ?x_0))
	(not (have_rock_analysis ?r_0 ?y_0))
	(not (have_rock_analysis ?x_1 ?py))
	(not (have_rock_analysis ?x_1 ?z_1))
	(not (have_soil_analysis ?r_0 ?py))
	(not (have_soil_analysis ?r_0 ?x_0))
	(not (have_soil_analysis ?r_0 ?y_0))
	(not (have_soil_analysis ?x_1 ?z_1))
	(not (visible ?py ?x_0))
	(not (visible ?py ?y_0))
	(not (visible ?x_0 ?py))
	(not (visible ?y_0 ?py))
	(visible ?py ?z_1)
	(visible ?x_0 ?y_0)
	(visible ?y_0 ?x_0)
	(visible ?z_1 ?py))
	:effect (and (at ?x_1 ?z_1)
		(communicated_rock_data ?py)
		(not (at ?x_1 ?py))
		))

)