(define (problem depotprob0) (:domain Depot)
(:objects
	depot0 depot1 depot2 depot3 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 - hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 depot3)
	(clear crate8)
	(at pallet4 distributor0)
	(clear crate4)
	(at pallet5 distributor1)
	(clear crate5)
	(at pallet6 distributor2)
	(clear crate7)
	(at truck0 distributor2)
	(= (current_load truck0) 0)
	(= (load_limit truck0) 454.0)
	(at truck1 depot0)
	(= (current_load truck1) 0)
	(= (load_limit truck1) 265.0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 depot3)
	(available hoist3)
	(at hoist4 distributor0)
	(available hoist4)
	(at hoist5 distributor1)
	(available hoist5)
	(at hoist6 distributor2)
	(available hoist6)
	(at crate0 distributor1)
	(on crate0 pallet5)
	(= (weight crate0) 88)
	(at crate1 distributor2)
	(on crate1 pallet6)
	(= (weight crate1) 85)
	(at crate2 distributor2)
	(on crate2 crate1)
	(= (weight crate2) 93)
	(at crate3 depot3)
	(on crate3 pallet3)
	(= (weight crate3) 40)
	(at crate4 distributor0)
	(on crate4 pallet4)
	(= (weight crate4) 28)
	(at crate5 distributor1)
	(on crate5 crate0)
	(= (weight crate5) 85)
	(at crate6 distributor2)
	(on crate6 crate2)
	(= (weight crate6) 59)
	(at crate7 distributor2)
	(on crate7 crate6)
	(= (weight crate7) 58)
	(at crate8 depot3)
	(on crate8 crate3)
	(= (weight crate8) 67)
	(= (fuel-cost) 0)
)

(:goal (and
		(on crate0 crate1)
		(on crate1 pallet1)
		(on crate2 pallet5)
		(on crate4 pallet4)
		(on crate5 pallet3)
		(on crate6 crate7)
		(on crate7 pallet0)
		(on crate8 pallet6)
	)
)

(:metric minimize (total-time)))
